### ISSUE TITLE
gatherlogs-reporter broken on Chef Workstation 20.6.62

### ISSUE THREAD

**Issue by nrgetik** [chef/gatherlogs-reporter#171]
# Describe the problem
Following getting a development environment up and running using the latest version of Chef Workstation (20.6.62 as of this writing), multiple errors are encountered when attempting to generate a report

## Software Version
* gatherlogs-reporter master branch
* Ubuntu 20.04 LTS
* Chef Workstation 20.6.62

```
vagrant@vagrant:~$ chef --version
Chef Workstation version: 20.6.62
Chef Infra Client version: 16.1.16
Chef InSpec version: 4.19.0
Chef CLI version: 3.0.4
Test Kitchen version: 2.5.1
Cookstyle version: 6.7.3
```

## Replication Case
1. Spin a new Ubuntu VM
2. Install `cmake`
3. Install Chef Workstation 20.6.62
4. Configure `$PATH` appropriately
5. Install `bundler:1.17.3`
6. Follow the remainder of https://github.com/chef/gatherlogs-reporter#local-development
7. Attempt a `gatherlog report` against an A2 log bundle

## Stacktrace
<details><summary> gatherlog-report output </summary>

```
vagrant@vagrant:/vagrant/automate.app.ford.com/20200627T1244370400$ gatherlog report
[1259, #<Thread:0x000000000173ae50 run>, #<Gem::LoadError: can't activate json-2.2.0, already activated json-2.3.0>, ["/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/specification.rb:2233:in `check_version_conflict'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/specification.rb:1367:in `activate'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:115:in `block in require'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:114:in `each'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:114:in `require'", "/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/utils/deprecation/config_file.rb:2:in `<top (required)>'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'", "/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/utils/deprecation.rb:4:in `<top (required)>'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'", "/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec.rb:8:in `<top (required)>'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:159:in `require'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:159:in `rescue in require'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:147:in `require'", "/home/vagrant/gatherlogs-reporter/lib/gatherlogs.rb:7:in `<top (required)>'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'", "/home/vagrant/gatherlogs-reporter/bin/gl-report:12:in `<main>'"]]
[1259, #<Thread:0x000000000173ae50 run>, #<RuntimeError: CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true>, ["/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:166:in `ensure in require'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:166:in `require'", "/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/utils/deprecation/config_file.rb:2:in `<top (required)>'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'", "/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/utils/deprecation.rb:4:in `<top (required)>'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'", "/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec.rb:8:in `<top (required)>'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:159:in `require'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:159:in `rescue in require'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:147:in `require'", "/home/vagrant/gatherlogs-reporter/lib/gatherlogs.rb:7:in `<top (required)>'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'", "/home/vagrant/gatherlogs-reporter/bin/gl-report:12:in `<main>'"]]
[1259, #<Thread:0x000000000173ae50 run>, #<RuntimeError: CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true>, ["/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:166:in `ensure in require'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:166:in `require'", "/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/utils/deprecation.rb:4:in `<top (required)>'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'", "/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec.rb:8:in `<top (required)>'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:159:in `require'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:159:in `rescue in require'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:147:in `require'", "/home/vagrant/gatherlogs-reporter/lib/gatherlogs.rb:7:in `<top (required)>'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'", "/home/vagrant/gatherlogs-reporter/bin/gl-report:12:in `<main>'"]]
[1259, #<Thread:0x000000000173ae50 run>, #<RuntimeError: CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true>, ["/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:166:in `ensure in require'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:166:in `require'", "/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec.rb:8:in `<top (required)>'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:159:in `require'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:159:in `rescue in require'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:147:in `require'", "/home/vagrant/gatherlogs-reporter/lib/gatherlogs.rb:7:in `<top (required)>'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'", "/home/vagrant/gatherlogs-reporter/bin/gl-report:12:in `<main>'"]]
[1259, #<Thread:0x000000000173ae50 run>, #<RuntimeError: CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true>, ["/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:166:in `ensure in require'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:166:in `require'", "/home/vagrant/gatherlogs-reporter/lib/gatherlogs.rb:7:in `<top (required)>'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'", "/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'", "/home/vagrant/gatherlogs-reporter/bin/gl-report:12:in `<main>'"]]
Traceback (most recent call last):
	5: from /home/vagrant/gatherlogs-reporter/bin/gl-report:12:in `<main>'
	4: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	3: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	2: from /home/vagrant/gatherlogs-reporter/lib/gatherlogs.rb:7:in `<top (required)>'
	1: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- inspec (LoadError)
	18: from /home/vagrant/gatherlogs-reporter/bin/gl-report:12:in `<main>'
	17: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	16: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	15: from /home/vagrant/gatherlogs-reporter/lib/gatherlogs.rb:7:in `<top (required)>'
	14: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:147:in `require'
	13: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:159:in `rescue in require'
	12: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:159:in `require'
	11: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec.rb:8:in `<top (required)>'
	10: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	 9: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	 8: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/utils/deprecation.rb:4:in `<top (required)>'
	 7: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	 6: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	 5: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/utils/deprecation/config_file.rb:2:in `<top (required)>'
	 4: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:114:in `require'
	 3: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:114:in `each'
	 2: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:115:in `block in require'
	 1: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/specification.rb:1367:in `activate'
/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/specification.rb:2233:in `check_version_conflict': can't activate json-2.2.0, already activated json-2.3.0 (Gem::LoadError)
	15: from /home/vagrant/gatherlogs-reporter/bin/gl-report:12:in `<main>'
	14: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	13: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	12: from /home/vagrant/gatherlogs-reporter/lib/gatherlogs.rb:7:in `<top (required)>'
	11: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:147:in `require'
	10: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:159:in `rescue in require'
	 9: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:159:in `require'
	 8: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec.rb:8:in `<top (required)>'
	 7: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	 6: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	 5: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/utils/deprecation.rb:4:in `<top (required)>'
	 4: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	 3: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	 2: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/utils/deprecation/config_file.rb:2:in `<top (required)>'
	 1: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:166:in `require'
/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:166:in `ensure in require': CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true (RuntimeError)
	12: from /home/vagrant/gatherlogs-reporter/bin/gl-report:12:in `<main>'
	11: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	10: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 9: from /home/vagrant/gatherlogs-reporter/lib/gatherlogs.rb:7:in `<top (required)>'
	 8: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:147:in `require'
	 7: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:159:in `rescue in require'
	 6: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:159:in `require'
	 5: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec.rb:8:in `<top (required)>'
	 4: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	 3: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:94:in `require'
	 2: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/utils/deprecation.rb:4:in `<top (required)>'
	 1: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:166:in `require'
/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:166:in `ensure in require': CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true (RuntimeError)
	9: from /home/vagrant/gatherlogs-reporter/bin/gl-report:12:in `<main>'
	8: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	7: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	6: from /home/vagrant/gatherlogs-reporter/lib/gatherlogs.rb:7:in `<top (required)>'
	5: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:147:in `require'
	4: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:159:in `rescue in require'
	3: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:159:in `require'
	2: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec.rb:8:in `<top (required)>'
	1: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:166:in `require'
/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:166:in `ensure in require': CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true (RuntimeError)
	5: from /home/vagrant/gatherlogs-reporter/bin/gl-report:12:in `<main>'
	4: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	3: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	2: from /home/vagrant/gatherlogs-reporter/lib/gatherlogs.rb:7:in `<top (required)>'
	1: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:166:in `require'
/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:166:in `ensure in require': CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true (RuntimeError)
	2: from /home/vagrant/gatherlogs-reporter/bin/gl-report:12:in `<main>'
	1: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:166:in `require'
/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:166:in `ensure in require': CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true (RuntimeError)
```

</details>

## Possible Solution
I have no clue what's happening

**Comment by nrgetik** [comment]
I think it's working again in Chef Workstation 20.7.96
